### ISSUE TITLE
Regarding the d_state and scanning direction questions

### ISSUE THREAD

**Issue by ZHUXIUJINChris** [aSleepyTree/FreqMamba#1]
Thank you for your outstanding work. I have a few questions:

1. Have you performed any selection and fusion of the results from multiple scanning directions?

2. You chose 4 for the d_state in your SSM, while the default is usually 16. Does this choice have a significant impact on the results?

3. Compared to LocalMamba, did you only use its Local scan part?

**Comment by aSleepyTree** [comment]
1. As the paper shows, the frequency-band branch differs from MambaIR in wavelet transform and scanning (see SS2D_local). The scan sequences in all four directions are stacked together and processed by self.selective_scan. I don't understand what selection and fusion mean。
2. I follow MambaIR(https://github.com/csguoh/MambaIR/blob/main/realDenoising/basicsr/models/archs/mambairunet_arch.py), where base_d_state is set to 4. I haven't tried 16, but I don't think that's the key point.
3. Yes, from local mamba I got the idea of local scanning in the wavelet domain. I referred to its method of local scanning.
