### ISSUE TITLE
SS2D_LOCAL

### ISSUE THREAD

**Issue by Yolo1-gguo** [aSleepyTree/FreqMamba#3]
Hello,Thank you for your outstanding work. I have a few questions:
 Is the code in the ss2d _ local part complete? May I ask how to solve this error problem?

Error message:
    x_dbl = torch.einsum("b k d l, k c d -> b k c l", xs.view(B, K, -1, L), self.x_proj_weight)
                                                      ^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[1, 4, -1, 921600]' is invalid for input of size 174182400

**Comment by aSleepyTree** [comment]
Your input tensor xs has a size of 174182400, which can't be trans to [1, 4, -1, 921600] ([B, K, -1, L]). The xs gained from `xs = torch.stack([x1, x2, x3, x4],dim=1)` is supposed to be divisible by 4. Did you change anything?

**Comment by Yolo1-gguo** [comment]
Hello, I used my own dataset and used your freqmamba _ arch module, and nothing has been changed to the things inside this module.

**Comment by yanghan0617** [comment]
> 您的输入张量 xs 的大小为 174182400，不能转换为 [1， 4， -1， 921600] （[B， K， -1， L]）。从中获得的 xs 应该能被 4 整除。你有没有改变什么？`xs = torch.stack([x1, x2, x3, x4],dim=1)`

请问你解决了吗

**Comment by Yolo1-gguo** [comment]
你好 我最后也没有解决这个问题




?。
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aSleepyTree/FreqMamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月16日(星期六) 晚上6:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aSleepyTree/FreqMamba] SS2D_LOCAL (Issue #3)





  
您的输入张量 xs 的大小为 174182400，不能转换为 [1， 4， -1， 921600] （[B， K， -1， L]）。从中获得的 xs 应该能被 4 整除。你有没有改变什么？xs = torch.stack([x1, x2, x3, x4],dim=1)
  
请问你解决了吗
